name: Register Archive Instance
description: Submit your Redd Archiver instance to the public registry
title: "[Registry] Add Instance: "
labels: ["registry", "new-instance"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Register Your Redd Archiver Instance

        Fill out this form to add your archive instance to the public registry and leaderboard.

        **Requirements:**
        - Your instance must be publicly accessible (clearnet or Tor)
        - The `/api/v1/stats` endpoint must be available
        - At least one URL (clearnet or Tor) is required

        **Auto-populated from API:**
        The following fields will be automatically fetched from your `/api/v1/stats` endpoint:
        - Instance name (can be overridden below)
        - Team ID (can be overridden below)
        - Tor URL (if detected by your instance)
        - Subreddits list
        - Features (API, Tor, User Pages)

        **Privacy Note:** Geolocation fields (region/country) are ignored for Tor-only instances.

  - type: input
    id: clearnet_url
    attributes:
      label: Clearnet URL
      description: Public HTTPS URL to your archive. Required if no Tor URL provided.
      placeholder: "https://archive.example.com"
    validations:
      required: false

  - type: input
    id: tor_url
    attributes:
      label: Tor Hidden Service URL
      description: .onion address. Required for tor-only instances, or to override API-detected value.
      placeholder: "http://abc123xyz.onion"
    validations:
      required: false

  - type: input
    id: instance_name
    attributes:
      label: Instance Name (Optional)
      description: Leave blank to use API-provided name. Override only if needed.
      placeholder: "Privacy Community Archive"
    validations:
      required: false

  - type: input
    id: team_name
    attributes:
      label: Team Name (Optional)
      description: Leave blank to use API-provided team_id. Override only if needed.
      placeholder: "Privacy Advocates Network"
    validations:
      required: false

  - type: input
    id: maintainer_github
    attributes:
      label: GitHub Username
      description: Your GitHub username (for contact and credit)
      placeholder: "username"
    validations:
      required: true

  - type: input
    id: preferred_contact
    attributes:
      label: Preferred Contact Method (Optional)
      description: Simplex, Matrix, Telegram, Signal, email, or other
      placeholder: "@user:matrix.org or simplex://contact/..."
    validations:
      required: false

  - type: dropdown
    id: hosting_type
    attributes:
      label: Hosting Type
      description: How is your archive hosted?
      options:
        - Self-hosted (VPS/dedicated server)
        - Homelab
        - GitHub Pages
        - Cloudflare Pages
        - Netlify
        - AWS S3
        - IPFS
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Server Region (Optional)
      description: Geographic region of your server (for redundancy tracking). Ignored for Tor-only instances.
      options:
        - North America
        - South America
        - Europe
        - Africa
        - Asia
        - Oceania
        - Other/Unknown
    validations:
      required: false

  - type: input
    id: country
    attributes:
      label: Country (Optional)
      description: Specific country if you want to share. Ignored for Tor-only instances.
      placeholder: "Germany, USA, Japan, etc."
    validations:
      required: false

  - type: checkboxes
    id: features
    attributes:
      label: Features (Optional)
      description: Additional features your archive supports. API and Tor are auto-detected.
      options:
        - label: User pages enabled (per-user activity pages)

  - type: input
    id: ipfs_cid
    attributes:
      label: IPFS CID (Optional)
      description: IPFS Content ID if hosted on IPFS
      placeholder: "QmXyz123..."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Anything else you'd like to share about your archive?
      placeholder: |
        - Update frequency: Daily/Weekly/Monthly
        - Special focus or filters applied
        - Bandwidth limits
        - Any unique features
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: My archive is publicly accessible (clearnet or Tor)
          required: true
        - label: The /api/v1/stats endpoint is working
          required: true
        - label: I will maintain reasonable uptime (>90%)
          required: true
        - label: I will notify if the instance goes offline permanently
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## What Happens Next?

        1. A maintainer will fetch your `/api/v1/stats` endpoint
        2. Instance name, subreddits, and features will be auto-populated
        3. Your instance will be added to the registry
        4. You'll appear on the public leaderboard within 24 hours

        **Thank you for contributing to the decentralized archive network!**
