name: Register Archive Instance
description: Submit your Redd Archiver instance to the public registry
title: "[Registry] Add Instance: "
labels: ["registry", "new-instance"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Register Your Redd Archiver Instance

        Fill out this form to add your archive instance to the public registry and leaderboard.

        **Requirements:**
        - Your instance must be publicly accessible
        - The `/api/v1/stats` endpoint must be available
        - Your archive should be reasonably up-to-date

  - type: input
    id: instance_name
    attributes:
      label: Instance Name
      description: A human-readable name for your archive
      placeholder: "Privacy Community Archive"
    validations:
      required: true

  - type: input
    id: clearnet_url
    attributes:
      label: Clearnet URL
      description: Public HTTPS URL to your archive
      placeholder: "https://archive.example.com"
    validations:
      required: true

  - type: input
    id: tor_url
    attributes:
      label: Tor Hidden Service URL (Optional)
      description: .onion address if you have a Tor mirror
      placeholder: "http://abc123xyz.onion"
    validations:
      required: false

  - type: input
    id: ipfs_cid
    attributes:
      label: IPFS CID (Optional)
      description: IPFS Content ID if hosted on IPFS
      placeholder: "QmXyz123..."
    validations:
      required: false

  - type: textarea
    id: subreddits
    attributes:
      label: Subreddits Archived
      description: List the subreddits in your archive (one per line)
      placeholder: |
        privacy
        privacytoolsIO
    validations:
      required: true

  - type: input
    id: team_name
    attributes:
      label: Team Name (Optional)
      description: If you're part of a team, enter the team name. Leave blank if solo.
      placeholder: "Privacy Advocates Network"
    validations:
      required: false

  - type: input
    id: maintainer_github
    attributes:
      label: GitHub Username
      description: Your GitHub username (for contact and credit)
      placeholder: "username"
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Email (Optional)
      description: Email for important notifications (kept private)
      placeholder: "admin@example.com"
    validations:
      required: false

  - type: input
    id: contact_matrix
    attributes:
      label: Matrix Contact (Optional)
      description: Matrix ID for team coordination
      placeholder: "@username:matrix.org"
    validations:
      required: false

  - type: dropdown
    id: hosting_type
    attributes:
      label: Hosting Type
      description: How is your archive hosted?
      options:
        - Self-hosted (VPS/dedicated server)
        - GitHub Pages
        - Cloudflare Pages
        - Netlify
        - AWS S3
        - IPFS
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Server Location (Optional)
      description: Geographic location of your server (for redundancy tracking)
      placeholder: "US-West, EU-Central, Asia-Pacific"
    validations:
      required: false

  - type: checkboxes
    id: features
    attributes:
      label: Features Enabled
      description: What features does your archive support?
      options:
        - label: Full-text search
        - label: Dark mode theme
        - label: Mobile-optimized
        - label: Tor accessible
        - label: IPFS pinned
        - label: REST API enabled

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Anything else you'd like to share about your archive?
      placeholder: |
        - Update frequency: Daily/Weekly/Monthly
        - Special focus or filters applied
        - Bandwidth limits
        - Any unique features
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: My archive is publicly accessible
          required: true
        - label: The /api/v1/stats endpoint is working
          required: true
        - label: I will maintain reasonable uptime (>90%)
          required: true
        - label: I will notify if the instance goes offline permanently
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## What Happens Next?

        1. A maintainer will verify your instance is accessible
        2. Your stats API will be checked for proper formatting
        3. Your instance will be added to the registry
        4. You'll appear on the public leaderboard within 24 hours

        **Thank you for contributing to the decentralized archive network!**
